- platform: xiaomi_miio
  host: 192.168.1.227
  token: !secret mi_plug1
  name: "Mi Plug 1"

- platform: xiaomi_miio
  host: 192.168.10.81
  token: !secret mi_plug2
  name: "Mi Plug 2"

- platform: xiaomi_miio
  host: 192.168.10.127
  token: !secret powerstrip
  name: "power strip"


- platform: broadlink_mp1
  host: 192.168.10.111
  mac: '78:0F:77:84:3F:DE'
  type: mp11
  friendly_name: 'MP1 Mibox'

- platform: broadlink_mp1
  host: 192.168.10.111
  mac: '78:0F:77:84:3F:DE'
  type: mp12
  friendly_name: 'MP1 Fan'

- platform: broadlink_mp1
  host: 192.168.10.111
  mac: '78:0F:77:84:3F:DE'
  type: mp13
  friendly_name: 'MP1 Tivi'

- platform: broadlink_mp1
  host: 192.168.10.111
  mac: '78:0F:77:84:3F:DE'
  type: mp14
  friendly_name: 'MP1 Soundbar'

- platform: broadlink
  host: 192.168.10.141
  mac: 'c8:f7:42:16:7f:98'
  switches:
    # Mitsubishi Fan:
    mitsubishi_fan_swing:
      friendly_name: "Mitsubishi Fan Swing"
      command_on: 'JgCGAGk1DiYOJg4NDQ0NDQ0mDg0NDQ0mDiYODQ0mDg0NDQwnDiYODQ0mDiYODQ0mDg0NDQ0NDQ0NDQ0mDg0NDQ0NDSYODQ0NDQ0NDQ0NDQ0NDQ0NDSYOJg4NDQ0NJQ8NDQ0NDQ0lDyUPJQ8NDQ0NDQ0NDQ0NDQ0NDQwODQ0NDSUPJRALDiUPAA0FAAA'
      command_off: 'JgCGAGk1DiYOJg4NDQ0NDQ0mDg0NDQ0mDiYODQ0mDg0NDQwnDiYODQ0mDiYODQ0mDg0NDQ0NDQ0NDQ0mDg0NDQ0NDSYODQ0NDQ0NDQ0NDQ0NDQ0NDSYOJg4NDQ0NJQ8NDQ0NDQ0lDyUPJQ8NDQ0NDQ0NDQ0NDQ0NDQwODQ0NDSUPJRALDiUPAA0FAAA'
    mitsubishi_fan_natural_mode:
      friendly_name: "Mitsubishi Fan Natural Mode"
      command_on: 'JgCGAGwyDyUQJBAKDwwODA4lEAoPCxAkDyUQCg8lEAoPCxAkECQQChAkDyUQBxMlDwoPCxAKEAoPCxAjEQkRCREJESMRCREJEAoRCREJEQkRCREKECMRIxEJEAoRIxAKEQkRCRAkESMQChEjEAoQChEJEAoRCRAKEAoRChAJECQRCRAkECQQAA0FAAA='
      command_off: 'JgCGAGszDiYOJg4MDgwODA4mDgwODA4mDiYODA4mDgwODA4mDiYODA4mDiYODA4mDgwODA4MDgwODA4mDgwODA4MDiYODA4MDgwODA4MDgwODA4MDiYOJg4MDgwOJg4MDgwODA4mDgwOJg4MDgwODA4MDgwODA4MDgwODA4MDgwOJQ8MDiUPAA0FAAA='
    mute:
      friendly_name: "Mute"
      command_on: 'JgBQAJWUEBEQERAREBEQMhAyERAQERExEDIQMhAyEBIPEREQEBIPlRARERAQERAREDIREBAREBIPMhAyEDIQEg8RETERMRExERAREBEQEDIRAA0FAAAAAAAAAAA='
      command_off: 'JgBQAJWUEBEQERAREBEQMhAyERAQERExEDIQMhAyEBIPEREQEBIPlRARERAQERAREDIREBAREBIPMhAyEDIQEg8RETERMRExERAREBEQEDIRAA0FAAAAAAAAAAA='


- platform: broadlink
  host: 192.168.10.144
  mac: 'c8:f7:42:16:81:cd'
  switches:
    #Hitachi Fan:
    hitachi_fan_swing:
      friendly_name: "Hitachi Fan Swing"
      command_on: 'JgBQAAABKZUTERM3ExISEhMSExITERM3EjgSExMRExISEhM3FBESEhM3EzcUNhM3FBETERQRExITERMSExETEhI4EzcTNxI4EwAFzQABKkkTAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKZUTERM3ExISEhMSExITERM3EjgSExMRExISEhM3FBESEhM3EzcUNhM3FBETERQRExITERMSExETEhI4EzcTNxI4EwAFzQABKkkTAA0FAAAAAAAAAAA='
    hitachi_fan_natural_mode:
      friendly_name: "Hitachi Fan Natural Mode"
      command_on: 'JgBIAAABKpQTEhI3ExISExISExISEhM3EzcTEhMRFBETERQ2ExITERQ2EzcTEhM3ExITERMSExETEhMRFDYUERM3EjgTNxM3EgANBQ=='
      command_off: 'JgBIAAABKpQTEhI3ExISExISExISEhM3EzcTEhMRFBETERQ2ExITERQ2EzcTEhM3ExITERMSExETEhMRFDYUERM3EjgTNxM3EgANBQ=='
    hitachi_fan_night_mode:
      friendly_name: "Hitachi Fan Night Mode"
      command_on: 'JgBIAAABKpQUERM3ExEUERMSExETExI3EzcTERQRExEUERM3ExITERQ2FDYUNhQREzcVDxQRExITERQRExEUNhQREzcTNxU1FQANBQ=='
      command_off: 'JgBIAAABKpQUERM3ExEUERMSExETExI3EzcTERQRExEUERM3ExITERQ2FDYUNhQREzcVDxQRExITERQRExEUNhQREzcTNxU1FQANBQ=='
    hitachi_fan_night_mode_10h:
      friendly_name: "Hitachi Fan Night Mode 10h"
      command_on: 'JgBIAAABKpQUERM3ExEUERMSExETExI3EzcTERQRExEUERM3ExITERQ2FDYUNhQREzcVDxQRExITERQRExEUNhQREzcTNxU1FQANBQ=='
      command_off: 'JgBIAAABKpQUERM3ExEUERMSExETExI3EzcTERQRExEUERM3ExITERQ2FDYUNhQREzcVDxQRExITERQRExEUNhQREzcTNxU1FQANBQ=='

- platform: template
  switches:
    xiaomi_fan_oscillate:
      value_template: "{{ is_state('sensor.xiaomi_fan_oscillate', 'True') }}"
      turn_on:
        service: fan.oscillate
        entity_id: fan.xiaomi_smart_fan
        data:
          oscillating: true
      turn_off:
        service: fan.oscillate
        entity_id: fan.xiaomi_smart_fan
        data:
          oscillating: false
- platform: template
  switches:
    xiaomi_fan_buzzer:
      value_template: "{{ is_state('sensor.xiaomi_fan_buzzer', 'True') }}"
      turn_on:
        service: fan.xiaomi_miio_set_buzzer_on
        data:
          entity_id: fan.xiaomi_smart_fan
      turn_off:
        service: fan.xiaomi_miio_set_buzzer_off
        data:
          entity_id: fan.xiaomi_smart_fan
- platform: template
  switches:
    xiaomi_fan_child_lock:
      value_template: "{{ is_state('sensor.xiaomi_fan_child_lock', 'True') }}"
      turn_on:
        service: fan.xiaomi_miio_set_child_lock_on
        data:
          entity_id: fan.xiaomi_smart_fan
      turn_off:
        service: fan.xiaomi_miio_set_child_lock_off
        data:
          entity_id: fan.xiaomi_smart_fan
- platform: template
  switches:
    xiaomi_fan_natural_mode:
      value_template: "{{ is_state('sensor.xiaomi_fan_natural_mode', 'on') }}"
      turn_on:
        service: fan.xiaomi_miio_set_natural_mode_on
        data:
          entity_id: fan.xiaomi_smart_fan
      turn_off:
        service: fan.xiaomi_miio_set_natural_mode_off
        data:
          entity_id: fan.xiaomi_smart_fan

#mqtt:
#bedroom-3
- platform: mqtt
  name: "Bedroom Ceiling Light"
  state_topic: "stat/bedroom-3/POWER1"
  command_topic: "cmnd/bedroom-3/POWER1"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Bedroom Wall Light 1"
  state_topic: "stat/bedroom-3/POWER2"
  command_topic: "cmnd/bedroom-3/POWER2"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Bedroom Led Light"
  state_topic: "stat/bedroom-3/POWER3"
  command_topic: "cmnd/bedroom-3/POWER3"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
#bedroom-2
- platform: mqtt
  name: "Bedroom Wall Light 2"
  state_topic: "stat/bedroom-2/POWER1"
  command_topic: "cmnd/bedroom-2/POWER1"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Bedroom All Light"
  state_topic: "stat/bedroom-2/POWER2"
  command_topic: "cmnd/bedroom-2/POWER2"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
#living-room-3
- platform: mqtt
  name: "Living Room Ceiling Light"
  state_topic: "stat/living-room-3/POWER1"
  command_topic: "cmnd/living-room-3/POWER1"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Living Room Wall Light 1"
  state_topic: "stat/living-room-3/POWER2"
  command_topic: "cmnd/living-room-3/POWER2"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Living Room Led Light"
  state_topic: "stat/living-room-3/POWER3"
  command_topic: "cmnd/living-room-3/POWER3"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
#gate
- platform: mqtt
  name: "Balcony Light (s)"
  state_topic: "stat/gate/POWER1"
  command_topic: "cmnd/gate/POWER1"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Gate Light"
  state_topic: "stat/gate/POWER2"
  command_topic: "cmnd/gate/POWER2"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
#balcony-2
- platform: mqtt
  name: "Balcony Light"
  state_topic: "stat/balcony-2/POWER1"
  command_topic: "cmnd/balcony-2/POWER1"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "Gate Light (s)"
  state_topic: "stat/balcony-2/POWER2"
  command_topic: "cmnd/balcony-2/POWER2"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
