title: Secutity
icon: mdi:motion-sensor
path: security
badges:
cards:
  - type: vertical-stack
    cards:
      - type: custom:decluttering-card
        template: header_text
        variables:
          - content: '##### Quick Access'
      - type: horizontal-stack
        cards:
          - !include ../decluttering_templates/blank-card.yaml
          - type: 'custom:decluttering-card'
            template: navigation_button
            variables:
              - entity: input_boolean.dummy1
              - name: Home
              - icon: home
              - size: 15%
              - aspect_ratio: 2/1
              - border-radius: 0px
              - show_label: false
              - show_state: false
              - justify-self-name: center
              - padding-left-name: 0px
              - color: '#ffffff'
              - margin-right: 0px
              - opacity: 0.8
              - off_name_color: var(--name-color-off)
              - tap_action:
                  action: navigate
                  navigation_path: /lovelace/home
                  haptic: light
              - hold_action:
                  action: navigate
                  navigation_path: /lovelace/home
                  haptic: light
          - type: 'custom:decluttering-card'
            template: navigation_button
            variables:
              - entity: input_boolean.dummy1
              - name: Lights
              - icon: ceiling-light
              - size: 15%
              - aspect_ratio: 2/1
              - border-radius: 0px
              - show_label: false
              - show_state: false
              - justify-self-name: center
              - padding-left-name: 0px
              - color: '#ffffff'
              - margin-right: 0px
              - opacity: 0.8
              - off_name_color: var(--name-color-off)
              - tap_action:
                  action: navigate
                  navigation_path: /lovelace/lights
                  haptic: light
              - hold_action:
                  action: navigate
                  navigation_path: /lovelace/lights
                  haptic: light
          - type: 'custom:decluttering-card'
            template: navigation_button
            variables:
              - entity: input_boolean.dummy1
              - name: Alarm
              - icon: shield-home
              - size: 15%
              - aspect_ratio: 2/1
              - border-radius: 0px
              - show_label: false
              - show_state: false
              - justify-self-name: center
              - padding-left-name: 0px
              - color: '#ffffff'
              - margin-right: 0px
              - opacity: 0.8
              - off_name_color: var(--name-color-off)
              - tap_action:
                  action: navigate
                  navigation_path: /lovelace/alarm
                  haptic: light
              - hold_action:
                  action: navigate
                  navigation_path: /lovelace/alarm
                  haptic: light
          - !include ../decluttering_templates/blank-card.yaml

  - type: vertical-stack
    cards:
      - type: custom:decluttering-card
        template: header_text
        variables:
          - content: '### Doors'
      - type: horizontal-stack
        cards:
          - !include ../decluttering_templates/blank-card.yaml
          - type: custom:decluttering-card
            template: sensor_button_card
            variables:
              - entity: binary_sensor.door_window_sensor_158d0001f369e9
              - name: Gate
              - icon: door-open
              - show_last_changed: true
              - tap_action: more-info
          - type: custom:button-card
            color_type: blank-card
            aspect_ratio: 1/1
          - type: custom:button-card
            color_type: blank-card
            aspect_ratio: 1/1
          - type: custom:button-card
            color_type: blank-card
            aspect_ratio: 1/1
          - !include ../decluttering_templates/blank-card.yaml
      - type: custom:decluttering-card
        template: header_text
        variables:
          - content: '### Motion'
      - type: horizontal-stack
        cards:
          - !include ../decluttering_templates/blank-card.yaml
          - type: custom:decluttering-card
            template: sensor_button_card
            variables:
              - entity: binary_sensor.motion_sensor_158d00023db50c
              - name: Living Room
              - icon: motion-sensor
              - show_last_changed: true
              - tap_action: more-info
          - type: custom:decluttering-card
            template: sensor_button_card
            variables:
              - entity: binary_sensor.motion_sensor_158d000275c945
              - name: Master Bedroom
              - icon: motion-sensor
              - show_last_changed: true
              - tap_action: more-info
          - type: custom:decluttering-card
            template: sensor_button_card
            variables:
              - entity: binary_sensor.motion_sensor_158d0002732c91
              - name: Second Bedroom
              - icon: motion-sensor
              - show_last_changed: true
              - tap_action: more-info
          - type: custom:decluttering-card
            template: sensor_button_card
            variables:
              - entity: binary_sensor.motion_sensor_158d0002760432
              - name: Kitchen
              - icon: motion-sensor
              - show_last_changed: true
              - tap_action: more-info
          - !include ../decluttering_templates/blank-card.yaml
